repos:
  - repo: local
    hooks:
      - id: run-pytest
        name: Run Pytest
        entry: pytest
        language: system  # assumes pytest is available in your environment
        types: [python]
        pass_filenames: false  # prevent passing filenames to pytest